version: '3.8'

services:
  # React Frontend (client)
  client:
    build: ./client
    ports:
      - "5173:80"
    environment:
      - CLIENT_URL=http://localhost:5173
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./client:/app

  # Express Backend (server)
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/kyusda
      - REDIS_URL=rediss://default:AeBaAAIjcDE4MzNkNDY1YThmYTU0YmM0OGJjZTI0ZGMxZDRlMGFhYnAxMA@first-flamingo-57434.upstash.io:6379
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SERVICE=gmail
      - SMTP_EMAIL=samuel202mwangi@gmail.com
      - SMTP_PASSWORD=wjyb fnvn vepa ztlt
      - PRAYER_DEPARTMENT_EMAIL=westscrip6378@gmail.com
      - ADMIN_EMAIL=westscrip6378@gmail.com
      - CLIENT_URL=http://localhost:5173
      - FRONTEND_URL=http://localhost:5173
      - SANITY_PROJECT_ID=sgmu0lrq
      - SANITY_DATASET=production
      - SANITY_API_TOKEN=sk0MvfKD103oqOs5PGzZMThedbLgDAsg1ojGTfBQdQdJMk3Jb9CpMgCp9Xv9YZDXBlYt3zFKN4hQOBSEMWcZAnICVAQZNydbTlMDl34Z7NGr8yB88fqIFFyw8nJmvwCtpAObFbFTreM1YTwcpIArWi4cBPZYM1l3FesmbB3U4xq9lrxjtRjZ
      - CLOUDINARY_CLOUD_NAME=ndekei
      - CLOUDINARY_API_KEY=936296614289215
      - CLOUDINARY_API_SECRET=6lC__lNWQfnACkSqG3FW52XiL1g
      - ACCESS_TOKEN=8AFPq0jR4O1z4lnJXoiOXOe6Emw69rP5WF2IarVQeFI=
      - ACCESS_TOKEN_EXPIRES=60
      - SECRET=kyusda2024secreteVALUETokenfb42c0f97adbfdb4c1d9e23e20bbf8f4a5a43028afe788419a0c29e2ae31ccb8
      - ACTIVATION_SECRET=11009876543210
    depends_on:
      - mongo
    # volumes:
    #   - ./server:/app

  # Sanity Studio (backend_sanity)
  sanity:
    build: ./backend_sanity
    ports:
      - "3333:3333"  # Maps 3333 on your machine to 3333 in container
    volumes:
      - ./backend_sanity:/app  # Uncomment for development

  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: