export { default as About } from "../components/About/About";
export { default as Testimonial } from "../components/Testimonials/Testimonials";
export { default as Departments } from "../components/Work/Departments";
export { default as Families } from "../components/Family/Families";
export { default as Gallery } from "../components/ImageGallery/ImageGallery";
export { default as Announcements } from "../components/Announcements/Announcement.jsx";
export { default as Footer } from "../components/Footer/Footer.jsx";
export { default as KyuSda } from "../components/Gallery/KyuSdaGallery.jsx";
export { default as Leader } from "../components/Leaders";
