// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajzxwxayjinwdomjzxjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqenh3eGF5amlud2RvbWp6eGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzMzNjMsImV4cCI6MjA2NTkwOTM2M30.rsNEMueZ0j5k1lbdvmaflZ1VEXw86LVWksw9gJQZiIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);