name: CI/CD - Deploy and Promote to Main

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: KYUSDA/church-system
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  build-api:
    name: Build Backend API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: KYUSDA/church-system
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  build-sanity:
    name: Build Sanity Studio
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend_sanity
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: KYUSDA/church-system
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  create-pr-to-staging:
    name: Create PR to Staging
    runs-on: ubuntu-latest
    needs:
      - build-client
      - build-api
      - build-sanity
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "CI: Auto PR from dev to staging"
          base: staging
          branch: dev
          title: "CI: Auto PR from dev to staging"
          body: |
            This PR was automatically created after all CI builds passed on `dev`.
