name: Build and test Node.js API from /server - kyusda-api (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install, Build, and Test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact (optional)
        run: zip -r ../server_build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-api-dev
          path: server_build.zip
