name: Build Sanity backend app - kyusda-sanity (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'backend_sanity/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        working-directory: ./backend_sanity
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for future deployment
        working-directory: ./backend_sanity
        run: zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sanity-package
          path: ./release.zip
