name: CI/CD - Deploy and Promote to Main

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  # --- Client Build ---
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  # --- Backend API Build ---
  build-api:
    name: Build Backend API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  # --- Sanity Studio Build ---
  build-sanity:
    name: Build Sanity Studio
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend_sanity
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  # --- Deploy to Staging ---
  deploy-staging:
    name: Deploy to Azure Staging
    runs-on: ubuntu-latest
    needs:
      - build-client
      - build-api
      - build-sanity
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'your-app-name'
          slot-name: 'staging'
          package: './'

  # --- Auto PR to Main ---
  create-pr-to-main:
    name: Create PR from Staging to Main
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create PR to Main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "CI: Auto PR from staging to main after deployment"
          base: main
          branch: staging
          title: "CI: Auto PR from staging to main"
          body: |
            This PR was automatically created after successful deployment to `staging`.
