name: Deploy Node.js API from /server to Azure Web App - kyusda-server (Staging)

on:
  push:
    branches:
      - staging
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip server build
        run: zip -r ../server_build.zip .

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-api
          path: server_build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-api

      - name: Unzip server build
        run: unzip -o server_build.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App (Staging Slot)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kyusda-server'
          slot-name: 'staging'
          package: .
