name: Deploy Sanity CMS to Azure Web App - kyusda-sanity (Staging)

on:
  push:
    branches:
      - staging
    paths:
      - backend_sanity/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build Sanity
        working-directory: ./backend_sanity
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          cd backend_sanity
          zip -r ../sanity_release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sanity-package
          path: sanity_release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sanity-package

      - name: Unzip artifact
        run: unzip sanity_release.zip -d sanity_dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App (Staging Slot)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kyusda-sanity'
          slot-name: 'staging'
          package: sanity_dist
